@echo off
mkdir d:\job-reqruitment\frontend\src\api
mkdir d:\job-reqruitment\frontend\src\components\common\buttons
mkdir d:\job-reqruitment\frontend\src\components\common\inputs
mkdir d:\job-reqruitment\frontend\src\components\common\cards
mkdir d:\job-reqruitment\frontend\src\components\common\tables
mkdir d:\job-reqruitment\frontend\src\components\common\modals
mkdir d:\job-reqruitment\frontend\src\components\common\forms
mkdir d:\job-reqruitment\frontend\src\components\navbar
mkdir d:\job-reqruitment\frontend\src\components\footer
mkdir d:\job-reqruitment\frontend\src\components\hero
mkdir d:\job-reqruitment\frontend\src\components\stats
mkdir d:\job-reqruitment\frontend\src\pages
mkdir d:\job-reqruitment\frontend\src\layouts
mkdir d:\job-reqruitment\frontend\src\hooks
mkdir d:\job-reqruitment\frontend\src\store
mkdir d:\job-reqruitment\frontend\src\context
mkdir d:\job-reqruitment\frontend\src\utils
mkdir d:\job-reqruitment\frontend\src\constants
mkdir d:\job-reqruitment\frontend\src\routes
mkdir d:\job-reqruitment\frontend\src\styles
mkdir d:\job-reqruitment\frontend\src\assets
mkdir d:\job-reqruitment\backend\config
mkdir d:\job-reqruitment\backend\controllers
mkdir d:\job-reqruitment\backend\services
mkdir d:\job-reqruitment\backend\repositories
mkdir d:\job-reqruitment\backend\middlewares
mkdir d:\job-reqruitment\backend\models
mkdir d:\job-reqruitment\backend\validators
mkdir d:\job-reqruitment\backend\routes
mkdir d:\job-reqruitment\backend\utils
mkdir d:\job-reqruitment\backend\emails
mkdir d:\job-reqruitment\backend\uploads
mkdir d:\job-reqruitment\backend\socket
mkdir d:\job-reqruitment\backend\cron
mkdir d:\job-reqruitment\backend\logs
echo All directories created successfully!